export function json(data,status=200,extraHeaders={}){const headers=new Headers({'Content-Type':'application/json; charset=UTF-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Pragma':'no-cache',...extraHeaders});return new Response(JSON.stringify(data),{status,headers})}
export function getCookie(request,name){const raw=request.headers.get('Cookie')||'';for(const part of raw.split(';')){const [k,...rest]=part.trim().split('=');if(k===name)return decodeURIComponent(rest.join('='));}return null}
export function getClientIp(request){return request.headers.get('CF-Connecting-IP')||request.headers.get('X-Forwarded-For')?.split(',')[0]?.trim()||'0.0.0.0'}
export async function sha256Hex(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value)));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
export function randomHex(bytes=32){const a=crypto.getRandomValues(new Uint8Array(bytes));return [...a].map(b=>b.toString(16).padStart(2,'0')).join('')}
export function cookie(name,value,maxAge,path='/'){return `${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=${path}; HttpOnly; Secure; SameSite=None; Partitioned`}
export function clearCookie(name,path='/'){return cookie(name,'',0,path)}
export function sameOrigin(request){const origin=request.headers.get('Origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin}catch{return false}}
export async function passwordHash(password,saltHex=randomHex(16)){const salt=new Uint8Array(saltHex.match(/.{1,2}/g).map(x=>parseInt(x,16)));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256);return `pbkdf2$120000$${saltHex}$${[...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,'0')).join('')}`}
export async function verifyPassword(password,stored){const p=String(stored||'').split('$');if(p.length!==4||p[0]!=='pbkdf2')return false;const iterations=Number(p[1]);if(!Number.isInteger(iterations)||iterations<100000||iterations>1000000||!/^[0-9a-f]{32}$/.test(p[2])||!/^[0-9a-f]{64}$/.test(p[3]))return false;const salt=new Uint8Array(p[2].match(/.{1,2}/g).map(x=>parseInt(x,16)));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations,hash:'SHA-256'},key,256);const got=[...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,'0')).join('');return constantTimeEqual(got,p[3])}
export function constantTimeEqual(a,b){a=String(a);b=String(b);if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
export async function rateLimit(env,key,limit,windowSeconds){const now=Date.now();const row=await env.DB.prepare('SELECT window_started_at,count FROM rate_limits WHERE key=?').bind(key).first();if(!row||now-Date.parse(String(row.window_started_at).replace(' ','T')+'Z')>=windowSeconds*1000){await env.DB.prepare('INSERT INTO rate_limits(key,window_started_at,count) VALUES(?,CURRENT_TIMESTAMP,1) ON CONFLICT(key) DO UPDATE SET window_started_at=CURRENT_TIMESTAMP,count=1').bind(key).run();return {allowed:true,remaining:Math.max(0,limit-1),retryAfter:0};}const count=Number(row.count||0);if(count>=limit){const started=Date.parse(String(row.window_started_at).replace(' ','T')+'Z');return {allowed:false,remaining:0,retryAfter:Math.max(1,Math.ceil((started+windowSeconds*1000-now)/1000))};}await env.DB.prepare('UPDATE rate_limits SET count=count+1 WHERE key=?').bind(key).run();return {allowed:true,remaining:Math.max(0,limit-count-1),retryAfter:0}}
export function rateHeaders(result){return {'Retry-After':String(result.retryAfter||0),'X-RateLimit-Remaining':String(result.remaining??0)}}
