import { sha256Hex, json, getCookie, getClientIp, randomHex, cookie, clearCookie, sameOrigin, rateLimit, rateHeaders, constantTimeEqual, verifyPassword } from '../../verifyAuth.js';
const COOKIE='teleshort_admin_session',SESSION_SECONDS=8*60*60,MICRO=1_000_000;
async function requireSession(request,env){const token=getCookie(request,COOKIE);if(!token)return null;const s=await env.DB.prepare("SELECT * FROM admin_sessions WHERE token_hash=? AND revoked_at IS NULL AND expires_at>datetime('now')").bind(await sha256Hex(token)).first();if(!s)return null;await env.DB.prepare('UPDATE admin_sessions SET last_seen_at=CURRENT_TIMESTAMP WHERE id=?').bind(s.id).run();return s;}
async function audit(env,action,type='',id='',metadata={}){await env.DB.prepare('INSERT INTO admin_audit_logs(id,action,target_type,target_id,metadata) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),action,type,id,JSON.stringify(metadata)).run();}
function parseBanners(raw){try{const x=JSON.parse(raw||'{}');return{header:String(x.header||''),left_sidebar:String(x.left_sidebar||''),right_sidebar:String(x.right_sidebar||''),bottom_banner:String(x.bottom_banner||'')}}catch{return{header:'',left_sidebar:'',right_sidebar:'',bottom_banner:''}}}
function publicSettings(s){return{cpm:Number(s?.cpm_micros||0)/MICRO,min_withdraw:Number(s?.min_withdraw_micros||0)/MICRO,refer_percent:s?.refer_percent??10,default_wait_seconds:s?.default_wait_seconds??10,heartbeat_seconds:s?.heartbeat_seconds??3,session_timeout_seconds:s?.session_timeout_seconds??600,payment_methods:s?.payment_methods||'',banner_ads:parseBanners(s?.banner_ads)};}
export async function onRequestPost(context){const{request,env}=context;try{const body=await request.json().catch(()=>({})),action=body.action,p=body.payload||{},ipHash=await sha256Hex(getClientIp(request));if(['login'].includes(action)&&!sameOrigin(request))return json({error:'Invalid request origin.'},403);
if(action==='login'){const rl=await rateLimit(env,`admin_login:ip:${ipHash}`,5,900);if(!rl.allowed)return json({error:'Too many admin login attempts. Try again later.',retry_after:rl.retryAfter},429,rateHeaders(rl));const password=String(body.password||'');let valid=false;if(env.ADMIN_PASSWORD_HASH)valid=await verifyPassword(password,env.ADMIN_PASSWORD_HASH);else if(env.ADMIN_PASSWORD)valid=constantTimeEqual(await sha256Hex(password),await sha256Hex(env.ADMIN_PASSWORD));if(!valid)return json({error:'Invalid credentials.'},401);const token=randomHex(32),csrf=randomHex(24);await env.DB.prepare('INSERT INTO admin_sessions(id,token_hash,csrf_token,expires_at) VALUES(?,?,?,?)').bind(crypto.randomUUID(),await sha256Hex(token),csrf,new Date(Date.now()+SESSION_SECONDS*1000).toISOString().replace('T',' ').replace('Z','')).run();await audit(env,'admin_login','','',{ip_hash:ipHash});return json({success:true,csrf_token:csrf},200,{'Set-Cookie':cookie(COOKIE,token,SESSION_SECONDS,'/api')});}
if(action==='logout'){const s=await requireSession(request,env);if(s)await env.DB.prepare('UPDATE admin_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE id=?').bind(s.id).run();return json({success:true},200,{'Set-Cookie':clearCookie(COOKIE,'/api')});}
const s=await requireSession(request,env);if(!s)return json({error:'Unauthorized.'},401);if(action==='get_csrf')return json({success:true,csrf_token:s.csrf_token});
if(['toggle_block','delete_user','process_withdrawal','save_settings'].includes(action)){const csrf=request.headers.get('X-CSRF-Token');if(!csrf||csrf!==s.csrf_token)return json({error:'CSRF validation failed.'},403);}
if(action==='get_dashboard'){const a=await env.DB.prepare('SELECT COUNT(*) n FROM users').first('n'),b=await env.DB.prepare('SELECT COUNT(*) n FROM users WHERE is_blocked=1').first('n'),c=await env.DB.prepare("SELECT COUNT(DISTINCT user_id) n FROM visit_attempts WHERE status='completed' AND created_at>=date('now')").first('n'),d=await env.DB.prepare("SELECT COALESCE(SUM(amount_micros),0) n FROM withdrawals WHERE status IN ('pending','processing')").first('n'),e=await env.DB.prepare("SELECT COALESCE(SUM(amount_micros),0) n FROM withdrawals WHERE status='paid'").first('n'),f=await env.DB.prepare('SELECT COUNT(*) n FROM visit_steps WHERE enabled=1').first('n');return json({totalUsers:Number(a||0),blockedUsers:Number(b||0),activeToday:Number(c||0),pendingAmount:Number(d||0)/MICRO,totalPaid:Number(e||0)/MICRO,activeSteps:Number(f||0)});}
if(action==='get_users'){const{results}=await env.DB.prepare('SELECT id,email,first_name,last_name,username,api_key_last4,balance_micros,total_earnings_micros,total_clicks,is_blocked,created_at FROM users ORDER BY created_at DESC LIMIT 300').all();return json({users:(results||[]).map(u=>({...u,balance:Number(u.balance_micros)/MICRO,total_earnings:Number(u.total_earnings_micros)/MICRO,api_key:`••••••••${u.api_key_last4}`}))});}
if(action==='toggle_block'){const id=String(p.user_id||''),blocked=p.is_blocked?1:0;if(!id)return json({error:'user_id required'},400);await env.DB.prepare('UPDATE users SET is_blocked=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(blocked,id).run();await audit(env,blocked?'block_user':'unblock_user','user',id,{});return json({success:true});}
if(action==='delete_user'){const id=String(p.user_id||'');if(!id)return json({error:'user_id required'},400);await env.DB.prepare('UPDATE users SET is_blocked=1,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(id).run();await audit(env,'soft_delete_user','user',id,{});return json({success:true});}
if(action==='get_withdrawals'){const{results}=await env.DB.prepare(`SELECT w.id,w.username,w.amount_micros,w.method,w.details,w.status,w.provider_reference,w.created_at,w.processed_at,u.email FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.created_at DESC LIMIT 300`).all();return json({withdrawals:(results||[]).map(w=>({...w,amount:Number(w.amount_micros)/MICRO}))});}
if(action==='process_withdrawal'){const{id:withdraw_id,withdraw_id:wid,status,provider_reference}=p, id=wid||withdraw_id;if(!id||!['processing','paid','rejected','failed'].includes(status))return json({error:'Invalid withdrawal action.'},400);const w=await env.DB.prepare('SELECT * FROM withdrawals WHERE id=?').bind(id).first();if(!w)return json({error:'Withdrawal not found.'},404);if(w.status!=='pending'&&!(w.status==='processing'&&['paid','failed'].includes(status)))return json({error:'Withdrawal is already finalized.'},409);if(status==='rejected'||status==='failed'){const r=await env.DB.batch([env.DB.prepare("UPDATE withdrawals SET status=?,processed_at=CURRENT_TIMESTAMP WHERE id=? AND status IN ('pending','processing')").bind(status,id),env.DB.prepare('UPDATE users SET balance_micros=balance_micros+?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(w.amount_micros,w.user_id),env.DB.prepare("INSERT INTO earnings_ledger(id,user_id,type,amount_micros,reference_id) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),w.user_id,'withdrawal_refund',w.amount_micros,id)]);if(!r[0]?.meta?.changes)return json({error:'Withdrawal state changed. Refresh.'},409);}else{const r=await env.DB.prepare("UPDATE withdrawals SET status=?,provider_reference=COALESCE(?,provider_reference),processed_at=CASE WHEN ?='paid' THEN CURRENT_TIMESTAMP ELSE processed_at END WHERE id=? AND status IN ('pending','processing')").bind(status,provider_reference||null,status,id).run();if(!r.meta.changes)return json({error:'Withdrawal state changed. Refresh.'},409);}await audit(env,'process_withdrawal','withdrawal',id,{status});return json({success:true});}
if(action==='get_settings'){return json({settings:publicSettings(await env.DB.prepare("SELECT * FROM settings WHERE id='default'").first())});}
if(action==='save_settings'){const u=p.updates||{},cpm=Number(u.cpm),min=Number(u.min_withdraw),ref=Number(u.refer_percent),wait=Number(u.default_wait_seconds),hb=Number(u.heartbeat_seconds),timeout=Number(u.session_timeout_seconds);if(!Number.isFinite(cpm)||cpm<0||cpm>100||!Number.isFinite(min)||min<=0||min>100000||!Number.isInteger(ref)||ref<0||ref>50||!Number.isInteger(wait)||wait<1||wait>120||!Number.isInteger(hb)||hb<2||hb>15||!Number.isInteger(timeout)||timeout<60||timeout>3600)return json({error:'Invalid settings range.'},400);const methods=String(u.payment_methods||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,20);if(!methods.length)return json({error:'At least one payment method is required.'},400);let bannerAds={header:'',left_sidebar:'',right_sidebar:'',bottom_banner:''};try{const b=u.banner_ads||{};for(const k of Object.keys(bannerAds)){const v=String(b[k]||'');if(v.length>20000)return json({error:'Each banner ad code must be 20,000 characters or less.'},400);bannerAds[k]=v} }catch{return json({error:'Invalid banner ad configuration.'},400)}await env.DB.prepare("UPDATE settings SET cpm_micros=?,min_withdraw_micros=?,refer_percent=?,default_wait_seconds=?,heartbeat_seconds=?,session_timeout_seconds=?,payment_methods=?,banner_ads=?,updated_at=CURRENT_TIMESTAMP WHERE id='default'").bind(Math.round(cpm*MICRO),Math.round(min*MICRO),ref,wait,hb,timeout,methods.join(', '),JSON.stringify(bannerAds)).run();await audit(env,'save_settings','','',{changed:Object.keys(u)});return json({success:true});}
if(action==='get_audit_logs'){const{results}=await env.DB.prepare('SELECT * FROM admin_audit_logs ORDER BY created_at DESC LIMIT 300').all();return json({logs:results||[]});}
return json({error:'Unknown action.'},400);}catch(e){console.error('ADMIN_API_ERROR',e);return json({error:'Internal server error.'},500);}}
