import { sha256Hex, json, getCookie, sameOrigin } from '../../verifyAuth.js';

const COOKIE='teleshort_admin_session';
async function session(request,env){const token=getCookie(request,COOKIE);if(!token)return null;const h=await sha256Hex(token);return env.DB.prepare("SELECT * FROM admin_sessions WHERE token_hash=? AND revoked_at IS NULL AND expires_at>datetime('now')").bind(h).first();}
async function audit(env,action,type='',id='',metadata={}){await env.DB.prepare('INSERT INTO admin_audit_logs(id,action,target_type,target_id,metadata) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),action,type,id,JSON.stringify(metadata)).run();}
function urlOk(v){try{const u=new URL(String(v||'').trim());return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null;}catch{return null;}}

export async function onRequestPost(context){const{request,env}=context;try{if(!sameOrigin(request))return json({error:'Invalid request origin.'},403);const s=await session(request,env);if(!s)return json({error:'Unauthorized.'},401);const body=await request.json().catch(()=>({})),action=body.action,p=body.payload||{};if(!['get_steps','create_step','update_step','delete_step','add_website','update_website','delete_website','reorder_websites','toggle_step'].includes(action))return json({error:'Unknown action.'},400);if(action!=='get_steps'){const csrf=request.headers.get('X-CSRF-Token');if(!csrf||csrf!==s.csrf_token)return json({error:'CSRF validation failed.'},403);}
if(action==='get_steps'){const{results:steps}=await env.DB.prepare('SELECT * FROM visit_steps ORDER BY step_number ASC').all();const{results:sites}=await env.DB.prepare('SELECT * FROM step_websites ORDER BY step_id,position ASC').all();return json({steps:(steps||[]).map(st=>({...st,websites:(sites||[]).filter(x=>x.step_id===st.id)}))});}
if(action==='create_step'){const title=String(p.title||'').trim().slice(0,120)||'New Step',description=String(p.description||'').trim().slice(0,500),wait=Math.max(1,Math.min(120,Number(p.wait_seconds||10)));const max=await env.DB.prepare('SELECT COALESCE(MAX(step_number),0) n FROM visit_steps').first('n');const n=Number(max||0)+1;const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO visit_steps(id,step_number,title,description,wait_seconds) VALUES(?,?,?,?,?)').bind(id,n,title,description,wait).run();await audit(env,'create_visit_step','visit_step',id,{step_number:n});return json({success:true,id});}
if(action==='update_step'){const id=String(p.id||''),title=String(p.title||'').trim().slice(0,120),description=String(p.description||'').trim().slice(0,500),wait=Math.max(1,Math.min(120,Number(p.wait_seconds||10)));if(!id)return json({error:'Step id required.'},400);await env.DB.prepare('UPDATE visit_steps SET title=?,description=?,wait_seconds=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(title,description,wait,id).run();await audit(env,'update_visit_step','visit_step',id,{});return json({success:true});}
if(action==='toggle_step'){const id=String(p.id||''),enabled=p.enabled?1:0;if(!id)return json({error:'Step id required.'},400);await env.DB.prepare('UPDATE visit_steps SET enabled=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(enabled,id).run();await audit(env,enabled?'enable_visit_step':'disable_visit_step','visit_step',id,{});return json({success:true});}
if(action==='delete_step'){const id=String(p.id||'');if(!id)return json({error:'Step id required.'},400);const row=await env.DB.prepare('SELECT step_number FROM visit_steps WHERE id=?').bind(id).first();if(!row)return json({error:'Step not found.'},404);await env.DB.prepare('DELETE FROM visit_steps WHERE id=?').bind(id).run();await env.DB.prepare('UPDATE visit_steps SET step_number=step_number-1 WHERE step_number>?' ).bind(row.step_number).run();await audit(env,'delete_visit_step','visit_step',id,{});return json({success:true});}
if(action==='add_website'){const stepId=String(p.step_id||''),u=urlOk(p.url);if(!stepId||!u)return json({error:'Valid step_id and URL are required.'},400);const step=await env.DB.prepare('SELECT id FROM visit_steps WHERE id=?').bind(stepId).first();if(!step)return json({error:'Step not found.'},404);const max=await env.DB.prepare('SELECT COALESCE(MAX(position),0) n FROM step_websites WHERE step_id=?').bind(stepId).first('n');const pos=Number(max||0)+1;const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO step_websites(id,step_id,title,url,position) VALUES(?,?,?,?,?)').bind(id,stepId,String(p.title||'Visit Website').trim().slice(0,120),u,pos).run();await audit(env,'add_visit_website','step_website',id,{step_id:stepId});return json({success:true,id});}
if(action==='update_website'){const id=String(p.id||''),u=urlOk(p.url);if(!id||!u)return json({error:'Website id and valid URL are required.'},400);await env.DB.prepare('UPDATE step_websites SET title=?,url=?,enabled=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(String(p.title||'Visit Website').trim().slice(0,120),u,p.enabled===false?0:1,id).run();await audit(env,'update_visit_website','step_website',id,{});return json({success:true});}
if(action==='delete_website'){const id=String(p.id||'');const row=await env.DB.prepare('SELECT step_id,position FROM step_websites WHERE id=?').bind(id).first();if(!row)return json({error:'Website not found.'},404);await env.DB.prepare('DELETE FROM step_websites WHERE id=?').bind(id).run();await env.DB.prepare('UPDATE step_websites SET position=position-1 WHERE step_id=? AND position>?' ).bind(row.step_id,row.position).run();await audit(env,'delete_visit_website','step_website',id,{});return json({success:true});}
if(action==='reorder_websites'){const stepId=String(p.step_id||''),ids=Array.isArray(p.ids)?p.ids.map(String):[];if(!stepId||!ids.length)return json({error:'step_id and ids required.'},400);const{results}=await env.DB.prepare('SELECT id FROM step_websites WHERE step_id=?').bind(stepId).all();const allowed=new Set((results||[]).map(x=>x.id));if(ids.length!==allowed.size||ids.some(x=>!allowed.has(x)))return json({error:'Invalid website order.'},400);const batch=ids.map((id,i)=>env.DB.prepare('UPDATE step_websites SET position=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND step_id=?').bind(i+1,id,stepId));await env.DB.batch(batch);await audit(env,'reorder_visit_websites','visit_step',stepId,{count:ids.length});return json({success:true});}
}catch(e){console.error('ADMIN_VISITS_ERROR',e);return json({error:'Internal server error.'},500);}}
