import { sha256Hex, json, getCookie, getClientIp, randomHex, sameOrigin, rateLimit, rateHeaders } from '../../verifyAuth.js';

const COOKIE='teleshort_user_session';
const MICRO=1_000_000;

async function getUser(request,env){const token=getCookie(request,COOKIE);if(!token)return null;const hash=await sha256Hex(token);const u=await env.DB.prepare(`SELECT s.id session_id,s.csrf_token,u.* FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>datetime('now') LIMIT 1`).bind(hash).first();if(!u||u.is_blocked)return null;await env.DB.prepare('UPDATE user_sessions SET last_seen_at=CURRENT_TIMESTAMP WHERE id=?').bind(u.session_id).run();return u;}
function dtMs(v){if(!v)return 0;const s=String(v);return new Date(s.endsWith('Z')?s:s.replace(' ','T')+'Z').getTime();}
async function settings(env){return env.DB.prepare("SELECT * FROM settings WHERE id='default'").first();}
async function currentTarget(env,session){const step=await env.DB.prepare('SELECT * FROM visit_steps WHERE step_number=? AND enabled=1').bind(session.current_step).first();if(!step)return null;const site=await env.DB.prepare('SELECT * FROM step_websites WHERE step_id=? AND position=? AND enabled=1').bind(step.id,session.current_position).first();if(!site)return null;return {step,site};}
async function nextTarget(env,stepNumber,position){const current=await env.DB.prepare('SELECT * FROM visit_steps WHERE step_number=? AND enabled=1').bind(stepNumber).first();if(current){const site=await env.DB.prepare('SELECT * FROM step_websites WHERE step_id=? AND position>? AND enabled=1 ORDER BY position ASC LIMIT 1').bind(current.id,position).first();if(site)return {step:current,site};}return env.DB.prepare('SELECT * FROM visit_steps WHERE enabled=1 AND step_number>? ORDER BY step_number ASC LIMIT 1').bind(stepNumber).first().then(async step=>step?{step,site:await env.DB.prepare('SELECT * FROM step_websites WHERE step_id=? AND enabled=1 ORDER BY position ASC LIMIT 1').bind(step.id).first()}:null);}
function payloadFor(session,target,attempt){const required=Number(target?.step?.wait_seconds||10);const activated=!!attempt?.last_heartbeat_at;const elapsed=activated&&attempt?.started_at?Math.max(0,Math.floor((Date.now()-dtMs(attempt.started_at))/1000)):0;return {session_id:session.id,step:session.current_step,position:session.current_position,step_title:target?.step?.title||`Step ${session.current_step}`,step_description:target?.step?.description||'',website:{id:target?.site?.id,title:target?.site?.title||'Visit Website',url:target?.site?.url},required_seconds:required,elapsed_seconds:Math.min(required,elapsed),activated,attempt_id:attempt?.id||null,status:session.status};}
async function proofHash(nonce,solution){return sha256Hex(`${nonce}:${solution}`)}
function validPow(hash,difficulty=4){return typeof hash==='string'&&hash.startsWith('0'.repeat(difficulty))}

export async function onRequestPost(context){const{request,env}=context;try{if(!sameOrigin(request))return json({error:'Invalid request origin.'},403);const body=await request.json().catch(()=>({})),action=body.action,p=body.payload||{};const user=await getUser(request,env);if(!user)return json({error:'Unauthorized. Please log in.'},401);const csrf=request.headers.get('X-CSRF-Token');if(!csrf||csrf!==user.csrf_token)return json({error:'CSRF validation failed.'},403);const ipHash=await sha256Hex(getClientIp(request));const limits={start:[30,60],heartbeat:[120,300],complete:[60,300],abandon:[30,60]};const lim=limits[action];if(lim){const rl=await rateLimit(env,`visit:${action}:user:${user.id}`,lim[0],lim[1]);if(!rl.allowed)return json({error:'Too many requests. Please slow down.',retry_after:rl.retryAfter},429,rateHeaders(rl));const ipRl=await rateLimit(env,`visit:${action}:ip:${await sha256Hex(getClientIp(request))}`,Math.max(10,Math.floor(lim[0]*2)),lim[1]);if(!ipRl.allowed)return json({error:'Too many requests from this network. Please slow down.',retry_after:ipRl.retryAfter},429,rateHeaders(ipRl));}

if(action==='challenge'){const challengeRl=await rateLimit(env,`visit:pow:user:${user.id}`,6,300);if(!challengeRl.allowed)return json({error:'Too many anti-bot challenges. Please try again later.',retry_after:challengeRl.retryAfter},429,rateHeaders(challengeRl));const nonce=crypto.randomUUID()+randomHex(8);await env.DB.prepare("INSERT INTO visit_pow_challenges(nonce,user_id,expires_at) VALUES(?,?,datetime('now','+120 seconds'))").bind(nonce,user.id).run();return json({success:true,nonce,difficulty:5,expires_in:120});}

if(action==='start'){const shortId=String(p.short_id||'').trim();if(!/^[A-Za-z0-9]{6,16}$/.test(shortId))return json({error:'Invalid short link.'},400);const link=await env.DB.prepare('SELECT l.*,cu.is_blocked creator_blocked FROM links l JOIN users cu ON cu.id=l.user_id WHERE l.short_id=? LIMIT 1').bind(shortId).first();if(!link)return json({error:'Short link not found.'},404);const linkIpRl=await rateLimit(env,`visit:${action}:linkip:${link.id}:${ipHash}`,10,300);if(!linkIpRl.allowed)return json({error:'Too many attempts for this link. Please try again later.',retry_after:linkIpRl.retryAfter},429,rateHeaders(linkIpRl));const nonce=String(p.pow_nonce||''),solution=String(p.pow_solution||'');if(!nonce||!/^\d{1,12}$/.test(solution))return json({error:'Anti-bot proof required.'},403);const challenge=await env.DB.prepare("SELECT nonce FROM visit_pow_challenges WHERE nonce=? AND user_id=? AND used_at IS NULL AND expires_at>datetime('now') LIMIT 1").bind(nonce,user.id).first();if(!challenge||!validPow(await proofHash(nonce,solution),5))return json({error:'Invalid or expired anti-bot proof.'},403);const consumed=await env.DB.prepare("UPDATE visit_pow_challenges SET used_at=CURRENT_TIMESTAMP WHERE nonce=? AND user_id=? AND used_at IS NULL AND expires_at>datetime('now')").bind(nonce,user.id).run();if(!consumed.meta.changes)return json({error:'Anti-bot proof already used.'},409);if(link.creator_blocked)return json({error:'This short link is unavailable.'},403);if(link.user_id===user.id)return json({error:'You cannot visit your own short link.'},403);
 const recent=await env.DB.prepare("SELECT id FROM click_logs WHERE link_id=? AND clicker_user_id=? AND created_at>=datetime('now','-24 hours') LIMIT 1").bind(link.id,user.id).first();if(recent)return json({error:'You already completed this short link within the last 24 hours.'},429);
 let session=await env.DB.prepare("SELECT * FROM visit_sessions WHERE user_id=? AND link_id=? AND status='active' AND expires_at>datetime('now') ORDER BY started_at DESC LIMIT 1").bind(user.id,link.id).first();
 if(!session){const firstStep=await env.DB.prepare('SELECT * FROM visit_steps WHERE enabled=1 ORDER BY step_number ASC LIMIT 1').first();if(!firstStep)return json({error:'No visit steps are configured by the administrator.'},503);const firstSite=await env.DB.prepare('SELECT * FROM step_websites WHERE step_id=? AND enabled=1 ORDER BY position ASC LIMIT 1').bind(firstStep.id).first();if(!firstSite)return json({error:'The first visit step has no active websites.'},503);const s=await settings(env),timeout=Math.max(60,Math.min(3600,Number(s?.session_timeout_seconds||600)));const exp=new Date(Date.now()+timeout*1000).toISOString().replace('T',' ').replace('Z','');const newId=crypto.randomUUID(),startedAt=new Date().toISOString().replace('T',' ').replace('Z','');await env.DB.prepare('INSERT OR IGNORE INTO visit_sessions(id,user_id,link_id,current_step,current_position,status,started_at,expires_at) VALUES(?,?,?,?,?,?,?,?)').bind(newId,user.id,link.id,firstStep.step_number,1,'active',startedAt,exp).run();session=await env.DB.prepare("SELECT * FROM visit_sessions WHERE user_id=? AND link_id=? AND status='active' AND expires_at>datetime('now') ORDER BY started_at DESC LIMIT 1").bind(user.id,link.id).first();}
 const target=await currentTarget(env,session);if(!target)return json({error:'No active website is configured for the current step.'},503);const old=await env.DB.prepare("SELECT * FROM visit_attempts WHERE session_id=? AND status='active' ORDER BY created_at DESC LIMIT 1").bind(session.id).first();const attempt=old||{id:crypto.randomUUID(),session_id:session.id,user_id:user.id,link_id:link.id,step_id:target.step.id,website_id:target.site.id,started_at:new Date().toISOString().replace('T',' ').replace('Z',''),last_heartbeat_at:null,status:'active'};if(!old){await env.DB.prepare('INSERT OR IGNORE INTO visit_attempts(id,session_id,user_id,link_id,step_id,website_id,started_at,required_seconds,status,ip_hash,user_agent_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(attempt.id,session.id,user.id,link.id,target.step.id,target.site.id,attempt.started_at,Number(target.step.wait_seconds||10),'active',ipHash,await sha256Hex(request.headers.get('User-Agent')||'')).run();const actual=await env.DB.prepare("SELECT * FROM visit_attempts WHERE session_id=? AND status='active' ORDER BY created_at DESC LIMIT 1").bind(session.id).first();if(actual)Object.assign(attempt,actual);}return json({success:true,original_url:link.original_url,...payloadFor(session,target,attempt)});}

if(action==='activate'){
  const id=String(p.attempt_id||''),sid=String(p.session_id||'');
  if(!id||!sid)return json({error:'Attempt is required.'},400);
  const attempt=await env.DB.prepare(`SELECT va.*,vs.status session_status,vs.expires_at FROM visit_attempts va JOIN visit_sessions vs ON vs.id=va.session_id WHERE va.id=? AND va.session_id=? AND va.user_id=? LIMIT 1`).bind(id,sid,user.id).first();
  if(!attempt)return json({error:'Visit attempt not found.'},404);
  if(attempt.status!=='active'||attempt.session_status!=='active')return json({error:'Visit attempt is no longer active.'},409);
  if(dtMs(attempt.expires_at)<Date.now()){await env.DB.prepare("UPDATE visit_sessions SET status='expired' WHERE id=? AND status='active'").bind(sid).run();return json({error:'Visit session expired.'},410);}
  if(attempt.last_heartbeat_at)return json({success:true,activated:true,elapsed_seconds:Math.max(0,Math.floor((Date.now()-dtMs(attempt.started_at))/1000))});
  const now=new Date().toISOString().replace('T',' ').replace('Z','');
  const r=await env.DB.prepare("UPDATE visit_attempts SET started_at=?,last_heartbeat_at=?,elapsed_seconds=0 WHERE id=? AND session_id=? AND user_id=? AND status='active' AND last_heartbeat_at IS NULL").bind(now,now,id,sid,user.id).run();
  if(!r.meta.changes)return json({error:'Visit activation failed. Please retry.'},409);
  return json({success:true,activated:true,elapsed_seconds:0,server_time:new Date().toISOString()});
}

if(action==='heartbeat'){const id=String(p.attempt_id||''),sid=String(p.session_id||'');if(!id||!sid)return json({error:'Attempt is required.'},400);const attempt=await env.DB.prepare(`SELECT va.*,vs.status session_status,vs.expires_at FROM visit_attempts va JOIN visit_sessions vs ON vs.id=va.session_id WHERE va.id=? AND va.session_id=? AND va.user_id=? LIMIT 1`).bind(id,sid,user.id).first();if(!attempt)return json({error:'Visit attempt not found.'},404);if(attempt.status!=='active'||attempt.session_status!=='active')return json({error:'Visit attempt is no longer active.'},409);if(!attempt.last_heartbeat_at)return json({error:'Open the website first.'},409);if(dtMs(attempt.expires_at)<Date.now()){await env.DB.prepare("UPDATE visit_sessions SET status='expired' WHERE id=? AND status='active'").bind(sid).run();return json({error:'Visit session expired.'},410);}await env.DB.prepare('UPDATE visit_attempts SET last_heartbeat_at=?,elapsed_seconds=CAST((julianday(CURRENT_TIMESTAMP)-julianday(started_at))*86400 AS INTEGER) WHERE id=? AND status=\'active\'').bind(new Date().toISOString().replace('T',' ').replace('Z',''),id).run();return json({success:true,server_time:new Date().toISOString()});}

if(action==='complete'){const sid=String(p.session_id||''),aid=String(p.attempt_id||'');if(!sid||!aid)return json({error:'Session and attempt are required.'},400);const attempt=await env.DB.prepare(`SELECT va.*,vs.current_step,vs.current_position,vs.status session_status,vs.expires_at,vs.link_id FROM visit_attempts va JOIN visit_sessions vs ON vs.id=va.session_id WHERE va.id=? AND va.session_id=? AND va.user_id=? LIMIT 1`).bind(aid,sid,user.id).first();if(!attempt)return json({error:'Visit attempt not found.'},404);if(attempt.status!=='active'||attempt.session_status!=='active')return json({error:'This visit attempt is no longer active.'},409);if(!attempt.last_heartbeat_at)return json({error:'Please open the website and start the visit timer first.'},409);if(dtMs(attempt.expires_at)<Date.now()){await env.DB.prepare("UPDATE visit_sessions SET status='expired' WHERE id=? AND status='active'").bind(sid).run();return json({error:'Visit session expired. Start again.'},410);}
 const elapsed=Math.floor((Date.now()-dtMs(attempt.started_at))/1000);const required=Number(attempt.required_seconds||10);const hbAge=attempt.last_heartbeat_at?Math.floor((Date.now()-dtMs(attempt.last_heartbeat_at))/1000):999;if(elapsed<required)return json({error:`Please stay for ${required-elapsed} more second(s).`,remaining:required-elapsed},429);
if(required>=5&&hbAge>15)return json({error:'Visit activity was not recently detected. Return to the visit page and try again.'},409);
 const target=await currentTarget(env,{current_step:attempt.current_step,current_position:attempt.current_position});if(!target||target.site.id!==attempt.website_id)return json({error:'Visit target changed. Please start again.'},409);
 const next=await nextTarget(env,attempt.current_step,attempt.current_position);
 if(next&&next.site){
   const nextStep=next.step.step_number,nextPos=Number(next.site.position),nextAttemptId=crypto.randomUUID(),now=new Date().toISOString().replace('T',' ').replace('Z','');
   const result=await env.DB.batch([
     env.DB.prepare("UPDATE visit_attempts SET completed_at=CURRENT_TIMESTAMP,last_heartbeat_at=CURRENT_TIMESTAMP,elapsed_seconds=?,status='completed' WHERE id=? AND status='active'").bind(elapsed,aid),
     env.DB.prepare("UPDATE visit_sessions SET current_step=?,current_position=? WHERE id=? AND status='active' AND EXISTS(SELECT 1 FROM visit_attempts WHERE id=? AND status='completed')").bind(nextStep,nextPos,sid,aid),
     env.DB.prepare("INSERT INTO visit_attempts(id,session_id,user_id,link_id,step_id,website_id,started_at,required_seconds,status,ip_hash,user_agent_hash) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM visit_sessions WHERE id=? AND current_step=? AND current_position=? AND status='active')").bind(nextAttemptId,sid,user.id,attempt.link_id,next.step.id,next.site.id,now,Number(next.step.wait_seconds||10),'active',ipHash,await sha256Hex(request.headers.get('User-Agent')||''),sid,nextStep,nextPos)
   ]);
   if(!result?.[0]?.meta?.changes||!result?.[2]?.meta?.changes)return json({error:'Completion transaction failed. Please retry.'},500);
   return json({success:true,step_completed:true,all_completed:false,...payloadFor({id:sid,current_step:nextStep,current_position:nextPos,status:'active'},next,{id:nextAttemptId})});
 }
 const link=await env.DB.prepare('SELECT * FROM links WHERE id=?').bind(attempt.link_id).first();if(!link)return json({error:'Link not found.'},404);const recent=await env.DB.prepare("SELECT id FROM click_logs WHERE link_id=? AND clicker_user_id=? AND created_at>=datetime('now','-24 hours') LIMIT 1").bind(link.id,user.id).first();if(recent){await env.DB.prepare("UPDATE visit_sessions SET status='rejected' WHERE id=? AND status='active'").bind(sid).run();return json({error:'This link was already completed recently.'},429);}
 const s=await settings(env),reward=Math.max(0,Math.floor(Number(s?.cpm_micros||0)/1000)),refPct=Math.max(0,Math.min(50,Number(s?.refer_percent||0)));const ref=refPct>0?await env.DB.prepare("SELECT r.referrer_user_id FROM referrals r JOIN users u ON u.id=r.referrer_user_id WHERE r.referred_user_id=? AND r.status='active' AND u.is_blocked=0 LIMIT 1").bind(link.user_id).first():null;const commission=ref?Math.floor(reward*refPct/100):0;const rewardId=crypto.randomUUID();const clickId=crypto.randomUUID();
 const statements=[
  env.DB.prepare("UPDATE visit_attempts SET completed_at=CURRENT_TIMESTAMP,last_heartbeat_at=CURRENT_TIMESTAMP,elapsed_seconds=?,status='completed' WHERE id=? AND status='active'").bind(elapsed,aid),
  env.DB.prepare("INSERT INTO visit_rewards(id,visit_session_id,user_id,link_id,amount_micros,referral_amount_micros) SELECT ?,?,?,?,?,? WHERE changes()=1").bind(rewardId,sid,link.user_id,link.id,reward,commission),
  env.DB.prepare("INSERT INTO click_logs(id,link_id,creator_user_id,clicker_user_id,ip_hash,user_agent_hash,risk_score,rewarded_micros) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM visit_rewards WHERE id=? AND visit_session_id=?)").bind(clickId,link.id,link.user_id,user.id,ipHash,await sha256Hex(request.headers.get('User-Agent')||''),0,reward,rewardId,sid),
  env.DB.prepare("UPDATE links SET clicks=clicks+1,earnings_micros=earnings_micros+? WHERE id=? AND EXISTS(SELECT 1 FROM visit_rewards WHERE id=? AND visit_session_id=? )").bind(reward,link.id,rewardId,sid),
  env.DB.prepare("UPDATE users SET balance_micros=balance_micros+?,total_earnings_micros=total_earnings_micros+?,total_clicks=total_clicks+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND is_blocked=0 AND EXISTS(SELECT 1 FROM visit_rewards WHERE id=? AND visit_session_id=?)").bind(reward,reward,link.user_id,rewardId,sid),
  env.DB.prepare("INSERT INTO earnings_ledger(id,user_id,type,amount_micros,reference_id,metadata) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM visit_rewards WHERE id=? AND visit_session_id=?)").bind(crypto.randomUUID(),link.user_id,'link_visit',reward,rewardId,JSON.stringify({short_id:link.short_id,visitor_id:user.id}),rewardId,sid),
 ];
 if(commission>0){statements.push(env.DB.prepare("UPDATE users SET balance_micros=balance_micros+?,total_earnings_micros=total_earnings_micros+?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND is_blocked=0 AND EXISTS(SELECT 1 FROM visit_rewards WHERE id=? AND visit_session_id=?)").bind(commission,commission,ref.referrer_user_id,rewardId,sid),env.DB.prepare("INSERT INTO earnings_ledger(id,user_id,type,amount_micros,reference_id,metadata) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM visit_rewards WHERE id=? AND visit_session_id=?)").bind(crypto.randomUUID(),ref.referrer_user_id,'referral_commission',commission,rewardId,JSON.stringify({source:'link_visit'}),rewardId,sid));}
 statements.push(env.DB.prepare("UPDATE visit_sessions SET status='completed',completed_at=CURRENT_TIMESTAMP WHERE id=? AND status='active' AND EXISTS(SELECT 1 FROM visit_rewards WHERE id=? AND visit_session_id=?)").bind(sid,rewardId,sid));
 const result=await env.DB.batch(statements);if(!result?.[1]?.meta?.changes||!result?.[result.length-1]?.meta?.changes)return json({error:'Completion transaction failed. Please retry.'},500);return json({success:true,all_completed:true,completed:true,rewarded:true,amount:reward/MICRO,original_url:link.original_url});}

if(action==='abandon'){const id=String(p.attempt_id||''),sid=String(p.session_id||'');if(!id||!sid)return json({error:'Attempt is required.'},400);await env.DB.prepare("UPDATE visit_attempts SET status='abandoned' WHERE id=? AND session_id=? AND user_id=? AND status='active'").bind(id,sid,user.id).run();return json({success:true});}
return json({error:'Unknown action.'},400);}catch(e){console.error('VISIT_API_ERROR',e);return json({error:'Internal server error.'},500);}}
